### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by skittles-mafia** [cosmohacker/SpoytifDownloadManager#7]
![image](https://github.com/cosmohacker/SpotifyDownloadManager/assets/93080455/ebd3b611-1701-4116-938e-70dd18fb8cc6)

**Comment by cosmohacker** [comment]
Oh hi!
As far as I understand, you are getting this error during the setup phase, if you're not please give me a little more detail about this error? I mean in which part of the program did you get this error?

**Comment by cosmohacker** [comment]
Any way bro i'm dropping here a solution for you assuming you get the error during installation:

https://github.com/pyinstaller/pyinstaller/issues/7412

**Comment by cosmohacker** [comment]
hello again i hope you doing well.
I'm closing this issiue because it's been so long... if you problem is still present please feel free to open again i ll try to do my best.
You are probably getting the error because of the path of the setup file. Do not put the file path in a place that does not contain latin characters in the next setup installation.(or next time)

https://discord.com/invite/4UWM4CZP4E
